version: "3.9"

services:
  db:
    image: postgres:15
    container_name: sklep_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sklep_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sklep_db"]
      interval: 2s
      timeout: 2s
      retries: 30

volumes:
  pgdata:
