services:
  db:
    image: postgres:16
    container_name: sklep_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sklep
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sklep"]
      interval: 3s
      timeout: 3s
      retries: 20
volumes:
  pg_data:
